import Head from "next/head";
import Header from "@/components/Header";
import Search from "@/components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Github Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-main-gray min-h-screen pt-8 px-32">
        <Header />
        <Search />
      </div>
    </>
  );
}
