import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { GlobeAltIcon } from "@heroicons/react/24/outline";
import { ClockIcon } from "@heroicons/react/24/outline";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import { getDaysSincePost } from "@/utils/dateUtils";

const JobDetail = ({ post }) => {
  const { title, fulltime, created, company, logo, city, details } = post;

  return (
    <>
      <Head>
        <title>Job Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-nowrap pt-6 gap-10">
        <div className="w-1/4 flex flex-col">
          <Link href="/">
            <div className="flex flex-nowrap gap-1 text-blue-700 text-xs font-light items-center hover:font-semibold">
              <ArrowLeftIcon className="w-3 h-3" />
              <p className="whitespace-nowrap">Back to search</p>
            </div>
          </Link>
          <p className="font-bold text-xs text-gray-400 pt-8">HOW TO APPLY</p>
          <p className="text-2xs pt-2">
            Please email a copy of your resume and online portfolio to{" "}
            <span className="text-blue-600 hover:cursor-pointer font-semibold">
              wes@kasisto.com
            </span>{" "}
            & CC{" "}
            <span className="text-blue-600 hover:cursor-pointer font-semibold">
              eric@kasisto.com
            </span>
          </p>
        </div>
        <div className="grow">
          <div className="flex flex-nowrap gap-4 items-center">
            <h1 className="text-2xl">{title}</h1>
            {fulltime && (
              <span className="text-[8px] text=[#334680] font-bold py-[2px] px-[4px] border border-[#334680] rounded-md w-fit">
                Full time
              </span>
            )}
          </div>
          <div className="flex flex-nowrap items-center gap-1 pt-1">
            <ClockIcon className="h-4 w-4 text-gray-300" />
            <p className="text-gray-400 font-semibold text-xs">
              {getDaysSincePost(created)}
            </p>
          </div>

          <div className="flex flex-nowrap gap-2 py-10">
            <div className="">
              <Image
                src={logo}
                alt="logo"
                width="42"
                height="42"
                className="w-10 h-10 object-cover rounded-md"
              />
            </div>
            <div className="flex flex-col justify-between">
              <h3 className="font-bold text-sm">{company}</h3>
              <div className="flex flex-nowrap gap-1 items-center">
                <GlobeAltIcon className="h-5 w-5 text-gray-300" />
                <p className="text-gray-400 text-2xs font-bold">{city}</p>
              </div>
            </div>
          </div>

          <div className="">{details}</div>
        </div>
      </div>
    </>
  );
};

export const getServerSideProps = async ({ query }) => {
  const res = await fetch(
    "https://6300ff309a1035c7f8fc2586.mockapi.io/jobposts"
  );
  const jobPosts = await res.json();
  const postId = query.id;
  const post = jobPosts.find((post) => post.id === postId);

  return {
    props: {
      post,
    },
  };
};
export default JobDetail;
